apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: test-new
spec:
  selector:
   matchLabels:
      app: test-app
  template:
     metadata:
        name: first-pod
        labels:
          app: test-app
     spec:
        containers: 
        - name: nginx-container
          image: nginx
    